server:
  port: 8000
spring:
  application:
    name: service-a   # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:                           # 指定数据源
    url: jdbc:mysql://***.***.***.***:3306/**?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: ********
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat
    minEvictableIdleTimeMillis: 300000		# 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
      instance:
        #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
        lease-renewal-interval-in-seconds: 10
        #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
        lease-expiration-duration-in-seconds: 5
        prefer-ip-address: true
#      management:
#        security:
#          enabled: false


mybatis:
  mapper-locations=classpath: com/hami/hamiservice1/v1/mapping/mapper/*.xml
  type-aliases-package: com.hami.hamiservice1

